# Introduction to Numpy

In [2]:
# Module import
import numpy as np

In [3]:
# Declaration of an n-dimensional array (ndarray)
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [4]:
# Scalar operations
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [5]:
# Array operations
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [6]:
# Data Shape
data.shape # Outer on the left, going to the right as one goes inner

(2, 3)

In [7]:
# Data Types
data.dtype

dtype('float64')

In [37]:
data1 = [[[1], [2], [3]], [[4], [5], [6]]]
arr1 = np.array(data1)
arr1.ndim

3

In [40]:
arr2 = np.ones_like(arr1)
arr2

array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [6]:
arr3 = np.array([1, 2, 3, 4, 6, 7, 9])
print(arr3.dtype)
arr4 = arr3.astype(np.float64)
print(arr4.dtype)

int32
float64


In [15]:
a = arr3[0:1]
a[0] = 5
arr3

array([5, 2, 3, 4, 6, 7, 9])

In [31]:
%%timeit

def fib(n):
    if n<= 1:
        return n
    return fib(n-1) + fib(n-2)
fib(32)

353 ms ± 1.43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:
%%timeit

np.arange(9).reshape(3,3)

503 ns ± 4.36 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [30]:
%%time

np.arange(9).reshape(3,3)

CPU times: total: 0 ns
Wall time: 0 ns


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
import pandas as pd

pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)
np.set_printoptions?

Signature:
np.set_printoptions(
    precision=None,
    threshold=None,
    edgeitems=None,
    linewidth=None,
    suppress=None,
    nanstr=None,
    infstr=None,
    formatter=None,
    sign=None,
    floatmode=None,
    *,
    legacy=None,
)
Docstring:
Set printing options.

These options determine the way floating point numbers, arrays and
other NumPy objects are displayed.

Parameters
----------
precision : int or None, optional
    Number of digits of precision for floating point output (default 8).
    May be None if `floatmode` is not `fixed`, to print as many digits as
    necessary to uniquely specify the value.
threshold : int, optional
    Total number of array elements which trigger summarization
    rather than full repr (default 1000).
    To always use the full repr without summarization, pass `sys.maxsize`.
edgeitems : int, optional
    Number of array items in summary at beginning and end of
    each dimension (default 3).
linewidth : int, optional
    The number of 

In [27]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])