# Pandas

## Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.array

<PandasArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
obj2 = pd.Series([4, 7, 5, 3], index = ["d", "b", "a", "c"])
obj2

d    4
b    7
a    5
c    3
dtype: int64

In [7]:
sdata = {
    "Ohio": 35000,
    "Texas": 71000,
    "Oregon": 16000,
    "Utah": 5000
}

obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [8]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [9]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [10]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [11]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [12]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [13]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [14]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrames

In [15]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [16]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [17]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [18]:
frame2 = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [19]:
frame2.columns
frame2.index = [6, 7, 8, 9, 10, 11]

In [20]:
frame2.iloc[1:5].loc[6:9, "year"]

7    2001
8    2002
9    2001
Name: year, dtype: int64

In [21]:
frame2bis = pd.DataFrame(data, columns = ["year", "state", "pop", "debt"])
frame2bis

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [22]:
frame2bis["debt"] = 16.5
frame2bis["debt"] = np.arange(6.)
frame2bis

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [23]:
val = pd.Series([-1.2, -1.5, -1.7, -2], index = ["two", "four", "five", 0])
frame2bis["add"] = val # Only present indices are added
frame2bis

year   state  pop  debt  add
0  2000    Ohio  1.5   0.0 -2.0
1  2001    Ohio  1.7   1.0  NaN
2  2002    Ohio  3.6   2.0  NaN
3  2001  Nevada  2.4   3.0  NaN
4  2002  Nevada  2.9   4.0  NaN
5  2003  Nevada  3.2   5.0  NaN

In [24]:
frame2bis["eastern"] = frame2bis["state"] == "Ohio"
frame2bis

year   state  pop  debt  add  eastern
0  2000    Ohio  1.5   0.0 -2.0     True
1  2001    Ohio  1.7   1.0  NaN     True
2  2002    Ohio  3.6   2.0  NaN     True
3  2001  Nevada  2.4   3.0  NaN    False
4  2002  Nevada  2.9   4.0  NaN    False
5  2003  Nevada  3.2   5.0  NaN    False

In [25]:
del frame2bis["eastern"]
frame2bis.columns

Index(['year', 'state', 'pop', 'debt', 'add'], dtype='object')

In [28]:
populations = {
    "Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
    "Nevada": {2001: 2.4, 2002: 2.9},
    "Arizona": {2000: "Heavy Boi", 2002: "Was ok"}
}
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada    Arizona
2000   1.5     NaN  Heavy Boi
2001   1.7     2.4        NaN
2002   3.6     2.9     Was ok

In [30]:
frame3.T # This discards the data type

2000 2001    2002
Ohio           1.5  1.7     3.6
Nevada         NaN  2.4     2.9
Arizona  Heavy Boi  NaN  Was ok

In [32]:
pdata = {
    "Ohio": frame3["Ohio"][:-1],
    "Nevada": frame3["Nevada"][:2]
}
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [35]:
arr = np.arange(5, 17).reshape(3, 4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
pd.DataFrame(arr)

0   1   2   3
0   5   6   7   8
1   9  10  11  12
2  13  14  15  16

In [48]:
lst = [{k: i ** k for k in range(1, 6)} for i in range(6)]
lst

[{1: 0, 2: 0, 3: 0, 4: 0, 5: 0},
 {1: 1, 2: 1, 3: 1, 4: 1, 5: 1},
 {1: 2, 2: 4, 3: 8, 4: 16, 5: 32},
 {1: 3, 2: 9, 3: 27, 4: 81, 5: 243},
 {1: 4, 2: 16, 3: 64, 4: 256, 5: 1024},
 {1: 5, 2: 25, 3: 125, 4: 625, 5: 3125}]

In [49]:
pd.DataFrame(lst)

1   2    3    4     5
0  0   0    0    0     0
1  1   1    1    1     1
2  2   4    8   16    32
3  3   9   27   81   243
4  4  16   64  256  1024
5  5  25  125  625  3125

In [52]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [54]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [55]:
obj3 = pd.Series(["blue", "purple", "yellow"], index = [0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [66]:
obj3.reindex(pd.RangeIndex(6), method = "ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [69]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3), index = ["a", "c", "d"], columns = ["Ohio", "Texas", "California"])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [70]:
frame2 = frame.reindex(["a", "b", "c", "d"])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [71]:
states = ["Texas", "Utah", "California"]
frame2.reindex(columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [78]:
frame2.reindex(states, axis="columns")

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [81]:
def alphabetic_list(start, end, step):
    alphabet = "abcdefghijklmnopqrstuvwxyz"
    return list(alphabet[start:end:step])

In [82]:
obj = pd.Series(np.arange(5.), index=alphabetic_list(0, 5, 1))
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [83]:
new_obj = obj.drop("c")
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [84]:
obj.drop(["c", "d"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [85]:
data = pd.DataFrame(np.arange(16).reshape(4, 4), index = ["Ohio", "Colorado", "Uath", "New York"], columns = ["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Uath        8    9     10    11
New York   12   13     14    15

In [93]:
data.drop("one", axis = "columns")

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Uath        9     10    11
New York   13     14    15

In [94]:
obj1 = pd.Series([1, 2, 3], index=[2, 0 ,1])
obj1

2    1
0    2
1    3
dtype: int64

In [98]:
obj1[2]

1

In [102]:
obj1[[0, 1, 2]] # This is secretly a .loc

0    2
1    3
2    1
dtype: int64

In [100]:
obj2 = pd.Series([1, 2, 3], index=alphabetic_list(0, 3, 1))
obj2

a    1
b    2
c    3
dtype: int64

In [101]:
obj2[2]

3

In [103]:
obj2[[0, 1, 2]] # The treatment differs depending on whether the index is integer based or not. This is secretly a .iloc

a    1
b    2
c    3
dtype: int64

In [104]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [105]:
obj1.loc[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [106]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [108]:
obj1.loc[2:1] # loc is inclusive

2    1
0    2
1    3
dtype: int64

In [109]:
obj1.iloc[0:2] # iloc is exclusive

2    1
0    2
dtype: int64

In [110]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [111]:
ser.iloc[-1]

2.0

In [127]:
df = pd.DataFrame(np.arange(12).reshape(4,3))
df

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [128]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [132]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list("abcde"))
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [133]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [134]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [135]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [142]:
arr[0]

array([0., 1., 2., 3.])

In [143]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [159]:
rng = np.random.default_rng(12345)
input_array = rng.standard_normal(size=(3,3))
input_array = np.arange(9.).reshape(3,3)
frame = pd.DataFrame(input_array, columns = list("bde"), index = ["Utah", "Ohio", "Texas"])
frame

b    d    e
Utah   0.0  1.0  2.0
Ohio   3.0  4.0  5.0
Texas  6.0  7.0  8.0

In [165]:
series = frame.iloc[:, 0]
series

Utah     0.0
Ohio     3.0
Texas    6.0
Name: b, dtype: float64

In [166]:
frame.sub(series, axis = "index")

b    d    e
Utah   0.0  1.0  2.0
Ohio   0.0  1.0  2.0
Texas  0.0  1.0  2.0

In [167]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)), columns=list("bde"), index = ["Utah", "Ohio", "Texas", "Oregon"])
frame

b         d         e
Utah    0.530469 -0.085926 -2.169970
Ohio   -0.955394 -1.941058 -0.577068
Texas  -0.713704 -1.526960  0.791608
Oregon  0.480574  1.118336  0.580601

In [168]:
np.abs(frame)

b         d         e
Utah    0.530469  0.085926  2.169970
Ohio    0.955394  1.941058  0.577068
Texas   0.713704  1.526960  0.791608
Oregon  0.480574  1.118336  0.580601

In [171]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1, axis="columns")

Utah      2.700439
Ohio      1.363990
Texas     2.318567
Oregon    0.637761
dtype: float64

In [182]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2, axis="columns")

min       max
Utah   -2.169970  0.530469
Ohio   -1.941058 -0.577068
Texas  -1.526960  0.791608
Oregon  0.480574  1.118336

In [185]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

b      d      e
Utah     0.53  -0.09  -2.17
Ohio    -0.96  -1.94  -0.58
Texas   -0.71  -1.53   0.79
Oregon   0.48   1.12   0.58

In [188]:
obj = pd.Series(np.arange(4), index = list("dabc"))
obj

d    0
a    1
b    2
c    3
dtype: int32

In [189]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [205]:
frame.sort_values(["b", "d"], ascending=[False, False])

b         d         e
Utah    0.530469 -0.085926 -2.169970
Oregon  0.480574  1.118336  0.580601
Texas  -0.713704 -1.526960  0.791608
Ohio   -0.955394 -1.941058 -0.577068

In [214]:
df = pd.DataFrame([[1, 1, 2, 3], [1, 2, 2, 3], [2, 3, 6, 1], [4, 1, 7, 8]], columns=list("abcd"))
df

a  b  c  d
0  1  1  2  3
1  1  2  2  3
2  2  3  6  1
3  4  1  7  8

In [222]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [223]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [225]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index = list("abcd"), columns = ["one", "two"])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [228]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [229]:
df.sum(axis = "columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [231]:
df.sum(skipna=False)

one   NaN
two   NaN
dtype: float64

In [233]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [234]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [235]:
obj = pd.DataFrame({"numbers": {0: 15, 1: 16, 2:23}, "strings": {0: "Hi", 1: "Itsame", 2: "Mario"}})
obj

numbers strings
0       15      Hi
1       16  Itsame
2       23   Mario

In [239]:
obj.loc[:,["strings"]].describe()

strings
count        3
unique       3
top         Hi
freq         1